version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: evac1_postgres
    hostname: postgres
    restart: unless-stopped
    env_file:
      - ./Eva_practica_C1/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./db:/sql-scripts:ro 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d evac1_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - tarea6-network

  
  # app:
  #   build:
  #     context: ./Eva_practica_C1
  #     dockerfile: Dockerfile
  #   container_name: Eva_practica
  #   restart: unless-stopped
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_NAME: evac1_db
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres123
  #     NODE_ENV: development
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./tarea6-dba:/app
  #     - /app/node_modules
  #     - /app/.next
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   command: npm run dev
  #   networks:
  #     - tarea6-network

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: tarea6_pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - tarea6-network

volumes:
  postgres_data:

networks:
  tarea6-network:
    driver: bridge